version: 2
jobs:
  node8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-yarn-deps-
      - run: yarn install
      - save_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn test
      - run: yarn build
  node10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-yarn-deps-
      - run: yarn install
      - save_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn test
      - run: yarn build
  docs:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-yarn-deps-
      - run: yarn install
      - save_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Generate docs
          command: |
            yarn generate-docs
            mkdir /tmp/webos-tv
            mv api /tmp/webos-tv
            git reset --hard
            cp {README.md,CODE_OF_CONDUCT.md} /tmp/webos-tv
            git checkout gh-pages
            shopt -s extglob
            rm -rf !(.|..|.git|_config.yml)
            mv /tmp/webos-tv/* .
            sed -nie '/## Index/,$p' api/README.md && rm api/README.mde
      - deploy:
          name: Deploy docs
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.name "${GITHUB_NAME}"
            git config user.email "${GITHUB_EMAIL}"
            git add .
            git commit -m "docs: Automatic generation"
            echo "Pushing to gh-pages branch..."
            git push -q https://${GITHUB_TOKEN}@github.com/Dabolus/webos-tv.git gh-pages
workflows:
  version: 2
  run_pipeline:
    jobs:
      - node8:
          filters:
            branches:
              only: master
      - node10:
          filters:
            branches:
              only: master
      - docs:
          filters:
            branches:
              only: master
          requires:
            - node8
            - node10
